### ISSUE TITLE
CSS comments

### ISSUE THREAD

**Issue by cvinczefullsail** [dehp3000/dehp3000.github.io#21]
Add CSS comments to organize your stylesheet. For example, Typography Defaults“ and “Default Structure”. See the Interrogative tutorials for details.

**Comment by dehp3000** [comment]
I realize I should have made more comments however due to time constraints I don't have many, I regret not being able to have enough.  I would have liked to have organized things better, I.e. /*centering*/ and everything to center under that comment, I have been building the pages the way the instructions show for class and That is html first competed and css last one piece at a time, However I think I should in the future attempt it as html section then css for that section and build each area separately to allow better commenting and better readable code later.
